[package]
name = "wikit"
version = "0.1.0"
authors = ["garebare <garedaiki@outlook.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ureq = "0.11.3"
xml-rs = "0.8"
termion = "*"